// src/app/ui/item-breadcrumb/item-breadcrumb/item-breadcrumb.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';

import { KaraageBreadcrumbs } from 'src/@types/karaage-breadcrumb';

import { Store, select } from '@ngrx/store';
import { selectBreadcrumbs } from '../../../ngrx/breadcrumb/breadcrumb.selectors'

//import { ReactItemBreadcrumb } from '../../_react-items/item-breadcrumb'

@Component({
  selector: 'item-breadcrumb',
  templateUrl: './item-breadcrumb.component.html',
  styleUrls: ['./item-breadcrumb.component.scss']
})
export class ItemBreadcrumbComponent implements OnInit {
  breadcrumbs$:Observable<{breadcrumbs:KaraageBreadcrumbs | undefined}> = this.store.pipe(select(selectBreadcrumbs));

  constructor(
    private store:Store,
  ) {}

  ngOnInit(): void {}
}

<card-origin *ngIf="(breadcrumbs$ | async)?.breadcrumbs?.length != 0">
  <ol class="breadcrumb" itemscope itemtype="https://schema.org/BreadcrumbList">
    <ng-container *ngFor="let breadcrumb of (breadcrumbs$ | async)?.breadcrumbs;let i = index">
      <li class="breadcrumb__item" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
        <a itemprop="item" [routerLink]="breadcrumb.path">
          <span itemprop="name">{{breadcrumb.name}}</span>
        </a>
        <meta itemprop="position" [content]="i"/>
      </li>
    </ng-container>
  </ol>
</card-origin>

// src/app/ui/_react-items/item-breadcrumb.tsx
import * as React from 'react';
import styled from 'styled-components'

import { ReactCardOrigin } from './card-origin'
import { KaraageBreadcrumbs } from 'src/@types/karaage-breadcrumb';

type prop = {
  breadcrumbs:KaraageBreadcrumbs
}

const List = styled.ol`
  list-style: none;
  display: flex;
  flex-wrap: nowrap;
  overflow-x: scroll;
  &::-webkit-scrollbar{
    display: none;
  }
`

const One = styled.li`
  margin-left: 4px;
  white-space: nowrap;
  a{
    color: var(--color-Highlight);
    font-size: 16px;
  }
  &:not(:last-of-type):after{
    content: " > ";
    margin-right: 4px;
  }
`

export const ReactItemBreadcrumb:React.FC<prop> = prop => {
  return (
    <ReactCardOrigin>
      <List attr-itemscope attr-itemtype="https://schema.org/BreadcrumbList">
        {
          prop.breadcrumbs.map((breadcrumb,i)=>{
            return (
              <One attr-itemprop="itemListElement" attr-itemscope attr-itemtype="https://schema.org/ListItem">
                <a attr-itemprop="item" href={breadcrumb.path.join("/")}>
                  <span attr-itemprop="name">{breadcrumb.name}</span>
                </a>
                <meta attr-itemprop="position" attr-content={i}/>
              </One>
            )
          })
        }
      </List>
    </ReactCardOrigin>
  );
}
