// src/app/shared/components/item-pagination/item-pagination/item-pagination.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'item-pagination',
  templateUrl: './item-pagination.component.html',
  styleUrls: ['./item-pagination.component.scss'],
})
export class ItemPaginationComponent implements OnInit {
  @Input() set maxCount(num: number | undefined) {
    if (num) this._maxCount = [...Array(num)].map((_, i) => i + 1);
  }
  @Input() count: number = 1;

  _maxCount: number[] = [];

  constructor() {}

  ngOnInit(): void {}
}

<div class="item-pagination">
  <div class="item-pagination__item" *ngFor="let count of _maxCount">
    <card-origin class="is-no-padding">
      <a class="item-pagination__item__inner" [routerLink]="count == 1 ? ['/']:['/page',count]">
        {{count}}
      </a>
    </card-origin>
  </div>
</div>

// src/app/ui/_react-items/item-pagination.tsx
import * as React from 'react';
import { ReactCardOrigin } from './card-origin'

import * as cssStyle from '../../styles/react-items/item-pagination.module.wcss'

type prop = {
  count: number,
  maxCount: number,
  onClick: Function
}

export const ReactItemPagination:React.FC<prop> = prop => {
  return (
    <div className={cssStyle.default["item-pagination"]}>
      {
        [...Array(prop.maxCount)].map((_,i)=>{
          return (
            <div className={cssStyle.default["item-pagination__item"]}>
              <ReactCardOrigin isNoPadding={true}>
                <a className={cssStyle.default["item-pagination__item__inner"]} href={ i != 0 ? '/?page=' + (i + 1):"/" } onClick={(e)=>{
                  e.preventDefault();
                  prop.onClick(e,i + 1)
                }}>
                  {i + 1}
                </a>
              </ReactCardOrigin>
            </div>
          )
        })
      }
    </div>
  );
}
