// src/app/shared/components/card-origin-article-loading/card-origin-article-loading/card-origin-article-loading.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'card-origin-article-loading',
  templateUrl: './card-origin-article-loading.component.html',
  styleUrls: ['./card-origin-article-loading.component.scss'],
})
export class CardOriginArticleLoadingComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<card-origin>
  <div class="card-origin-article-loading">
    <div class="card-origin-article-loading__image"></div>

    <div class="card-origin-article-loading__content">
      <div class="card-origin-article-loading__content__title"></div>
    </div>
  </div>
</card-origin>

// src/app/ui/react-items/card-origin-article-loading.tsx
import * as React from 'react';

import { ReactCardOrigin } from './card-origin'
import * as cssStyle from '../../styles/react-items/card-origin-article-loading.module.wcss'

export const ReactCardOriginArticleLoading:React.FC = () => {
  return (
    <ReactCardOrigin>
      <div className={cssStyle.default["card-origin-article-loading"]}>
        <div className={cssStyle.default["card-origin-article-loading__image"]}/>

        <div className={cssStyle.default["card-origin-article-loading__content"]}>
          <div className={cssStyle.default["card-origin-article-loading__content__title"]}/>
        </div>
      </div>
    </ReactCardOrigin>
  );
}
